# Définition des sources de données
sources:
  - name: dbt_papesc_datagouv  # Nom de la source
    schema: dbt_papesc_datagouv
    tables:       # Liste des tables dans cette source
      - name: vehicules  # Nom de la table

